ARG IMAGE_EXT

ARG BASE=7.0.9ec4
ARG REGISTRY=ghcr.io/epics-containers
ARG RUNTIME=${REGISTRY}/epics-base${IMAGE_EXT}-runtime:${BASE}
ARG DEVELOPER=${REGISTRY}/epics-base${IMAGE_EXT}-developer:${BASE}

##### build stage ##############################################################
FROM  ${DEVELOPER} AS developer

# The devcontainer mounts the project root to /epics/generic-source
# Using the same location here makes devcontainer/runtime differences transparent.
ENV SOURCE_FOLDER=/epics/generic-source
# connect ioc source folder to its know location
RUN ln -s ${SOURCE_FOLDER}/ioc ${IOC}

# Get the current version of ibek
COPY requirements.txt requirements.txt
RUN uv pip install --upgrade -r requirements.txt

WORKDIR ${SOURCE_FOLDER}/ibek-support

COPY ibek-support-dls/_ansible _ansible
ENV PATH=$PATH:${SOURCE_FOLDER}/ibek-support/_ansible

COPY ibek-support-dls/iocStats/ iocStats
RUN ansible.sh iocStats

COPY ibek-support-dls/pvlogging/ pvlogging/
RUN ansible.sh pvlogging

COPY ibek-support-dls/autosave/ autosave
RUN ansible.sh autosave

COPY ibek-support-dls/asyn/ asyn/
RUN ansible.sh -v R4-44-2 asyn

COPY ibek-support-dls/busy/ busy/
RUN ansible.sh -v R1-7-3 busy


COPY ibek-support-dls/StreamDevice/ StreamDevice/
RUN ansible.sh StreamDevice

COPY ibek-support-dls/calc/ calc/
RUN ansible.sh calc

COPY ibek-support-dls/sscan/ sscan/
RUN ansible.sh sscan

COPY ibek-support-dls/motor/ motor/
RUN ansible.sh motor

COPY ibek-support-dls/motorMotorSim/ motorMotorSim/
RUN ansible.sh motorMotorSim

COPY ibek-support-dls/ADCore/ ADCore/
RUN ansible.sh ADCore

COPY ibek-support-dls/ADGenICam ADGenICam/
RUN ansible.sh -v R1-10 ADGenICam

COPY ibek-support-dls/ADAravis/ ADAravis/
RUN ansible.sh ADAravis

COPY ibek-support-dls/ADSimDetector ADSimDetector/
RUN ansible.sh ADSimDetector

# COPY ibek-support-dls/lakeshore340  lakeshore340/
# RUN  ansible.sh lakeshore340

COPY ibek-support-dls/modbus/ modbus/
RUN ansible.sh modbus

COPY ibek-support-dls/motorNewport motorNewport/
RUN ansible.sh motorNewport

COPY ibek-support-dls/sequencer/ sequencer/
RUN ansible.sh sequencer

COPY ibek-support-dls/ffmpegServer/ ffmpegServer
RUN ansible.sh ffmpegServer

COPY ibek-support-dls/pvxs pvxs
RUN ansible.sh pvxs

COPY ibek-support/pcas pcas
RUN ansible.sh pcas

# get the ioc source and build it
COPY ioc/ ${SOURCE_FOLDER}/ioc
RUN ansible.sh ioc

WORKDIR ${SOURCE_FOLDER}/ibek-support-infn
# Single COPY to keep layer depth under Docker's 127-layer hard limit.
COPY ibek-support-infn/ ./

RUN ansible.sh AgilentXgs600 && \
    ansible.sh biltItest && \
    ansible.sh sigmaPhiStart && \
    ansible.sh icpdas && \
    ansible.sh maccaferriPS && \
    ansible.sh ocemE642 && \
    ansible.sh danfysik && \
    ansible.sh easy-driver-epics && \
    ansible.sh agilentipcmini && \
    ansible.sh agilent4uhv && \
    ansible.sh smc && \
    ansible.sh Tektronix_MSO58LP && \
    ansible.sh caenelsPS && \
    ansible.sh motorMicos && \
    ansible.sh cagateway && \
    ansible.sh hazemeyer && \
    ansible.sh ppt-modulator && \
    ansible.sh scandinova-scandicat-mod && \
    ansible.sh polyscience && \
    ansible.sh plc-elinp && \
    ansible.sh technosoft-tml-motor && \
    ansible.sh thorlabsApt && \
    ansible.sh Danfysik_HallProbes && \
    ansible.sh scandinova-mod-k400 && \
    ansible.sh menlo && \
    ansible.sh psEEI && \
    ansible.sh TTI 


EXPOSE 5064 5065


